In [2]:
import pandas as pd 
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [3]:
# ============================================================
# 🟢 LEVEL 1 — PANDAS BASICS
# ============================================================

# Q1. Load and inspect the data
# Load the CSV into a DataFrame and display:
# - First 5 rows
# - Last 5 rows
# - Number of rows and columns
# - Column names
# - Data types of all columns


# Q2. Basic statistics
# Find:
# - Total number of records
# - Total sales
# - Total profit
# - Total quantity sold
# - Average sales
# - Average profit


# Q3. Select columns
# Create a new DataFrame containing only:
# - Customer Name
# - Segment
# - City
# - State
# - Category
# - Sales
# - Profit


# Q4. Filtering
# Find all records where:
# 1. Sales > 500
# 2. Profit > 100
# 3. Discount > 0
# 4. Category == "Furniture"
#
# Then find records where:
# Sales > 500 AND Profit < 0


# Q5. Sorting
# Sort the DataFrame:
# 1. By Sales from highest to lowest
# 2. By Profit from lowest to highest
# 3. By Category ascending and Sales descending


# ============================================================
# 🟢 LEVEL 2 — DATA CLEANING & TRANSFORMATION
# ============================================================

# Q6. Missing values
# Find:
# - Number of missing values in each column
# - Total missing values in the entire DataFrame
# - Columns containing at least one missing value


# Q7. Unique values
# Find:
# - Number of unique customers
# - Number of unique products
# - Number of unique cities
# - Number of unique states
# - Unique categories
# - Unique sub-categories
# - Unique regions


# Q8. value_counts()
# Find the number of records for each:
# - Category
# - Sub-Category
# - Segment
# - Region
# - Ship Mode
# - Profit Status
# - Discount Status


# Q9. Create a new column
# Create a column called "Profit Margin":
#
# Profit Margin = Profit / Sales * 100
#
# Display:
# - Product Name
# - Sales
# - Profit
# - Profit Margin
#
# for the first 10 rows.


# Q10. Use apply()
# Create a column called "Sales Level":
#
# Sales < 100          -> "Low"
# Sales between 100-500 -> "Medium"
# Sales > 500          -> "High"


# ============================================================
# 🟡 LEVEL 3 — GROUPBY
# ============================================================

# Q11. Category analysis
# Calculate total:
# - Sales
# - Profit
# - Quantity
#
# for each Category.


# Q12. Region analysis
# Find the total Sales and Profit for each Region.
#
# Then sort the result by Profit in descending order.


# Q13. Sub-category analysis
# Find the average Sales for every Sub-Category.
#
# Which Sub-Categories have an average Sales value greater than 200?


# Q14. Customer analysis
# Find the top 10 customers by total Sales.
#
# Output:
# - Customer Name
# - Total Sales


# Q15. Customer profitability
# Find:
# - Top 10 customers based on total Profit
# - 10 customers with the lowest total Profit


# Q16. Multiple aggregations
# For each Category, calculate:
# - Total Sales
# - Average Sales
# - Total Profit
# - Average Profit
# - Total Quantity
#
# Use .agg()


# ============================================================
# 🟠 LEVEL 4 — DATE ANALYSIS
# ============================================================

# Q17. Convert dates and extract information
# Convert:
# - Order Date
# - Ship Date
#
# into proper datetime columns.
#
# Then create:
# - Order Year
# - Order Month
# - Order Day


# Q18. Yearly sales
# Calculate total:
# - Sales
# - Profit
# - Quantity
#
# for each Order Year.


# Q19. Monthly sales
# Find total Sales for each month.
#
# Then determine which month has the highest total Sales.


# Q20. Shipping time
# Create a column called "Shipping Days":
#
# Shipping Days = Ship Date - Order Date
#
# Find:
# - Average shipping days
# - Maximum shipping days
# - Minimum shipping days
# - Orders taking more than 5 days
#
# Also identify records where Shipping Days is negative.


# ============================================================
# 🔴 LEVEL 5 — ADVANCED PANDAS
# ============================================================

# Q21. Category + Region
# Create a table showing total Profit for every
# Category × Region combination.
#
# Solve using groupby() or pivot_table().


# Q22. Pivot table
# Create a pivot table where:
# - Rows = Region
# - Columns = Category
# - Values = Sales
# - Aggregation = sum


# Q23. Most profitable products
# Find the top 10 products based on total Profit.
#
# Remember:
# The same product can appear in multiple rows,
# so group the products first.


# Q24. Loss-making products
# Find products where:
#
# Total Sales > 1000
# AND
# Total Profit < 0
#
# Group the data first, then filter the result.


# Q25. Discount analysis
# Calculate the average Profit for each Discount level:
#
# 0%
# 10%
# 20%
# 30%
# 40%
# 50%
#
# Then compare it with the number of records
# at each Discount level.


# ============================================================
# 🔥 LEVEL 6 — REAL DATA ANALYSIS
# ============================================================

# Q26. Category profitability
# For each Category calculate:
# - Total Sales
# - Total Profit
# - Profit Margin
#
# Profit Margin =
# Total Profit / Total Sales * 100


# Q27. Customer purchase behavior
# Find customers who:
# - Have at least 10 orders/records
# - Have total Sales greater than 5000
# - Have positive total Profit


# Q28. Repeat customers
# Find customers who purchased products in more than one year.
#
# Output:
# - Customer Name
# - Number of Years
# - Total Sales


# Q29. Product performance
# For every Sub-Category calculate:
# - Total Sales
# - Total Profit
# - Average Discount
# - Total Quantity
# - Profit Margin
#
# Then identify Sub-Categories with negative total Profit.


# Q30. Business-style analysis
# Find the top 10 States by total Sales.
#
# For those states, show:
# - State
# - Total Sales
# - Total Profit
# - Average Discount
# - Total Quantity
# - Profit Margin
#
# Sort by Total Sales descending.


# ============================================================
# 💀 CHALLENGE QUESTIONS
# ============================================================

# Q31. Best-selling product in each category
# For every Category, find the product with the
# highest total Sales.
#
# Expected output:
# - Category
# - Product Name
# - Total Sales


# Q32. Most profitable customer in each region
# For every Region, find the customer with the
# highest total Profit.


# Q33. Loss percentage
# Calculate Loss Percentage for each Category:
#
# Loss Percentage =
# Number of loss-making records / Total records * 100
#
# A loss-making record means Profit < 0.


# Q34. Discount vs profitability
# For each Discount level calculate:
# - Number of Orders
# - Total Sales
# - Total Profit
# - Average Profit
# - Percentage of loss-making records


# Q35. 🚀 FINAL PANDAS CHALLENGE
#
# Create a complete Sales Performance Summary containing:
#
# - Region
# - Category
# - Total Sales
# - Total Profit
# - Total Quantity
# - Average Discount
# - Profit Margin
# - Number of Orders
#
# Profit Margin =
# Total Profit / Total Sales * 100
#
# Then sort the result by:
# Region ascending
# and Total Sales descending
#
# This question should use:
# - groupby()
# - agg()
# - reset_index()
# - calculated columns
# - sorting
#
# ------------------------------------------------------------
# END OF PANDAS PRACTICE
# ------------------------------------------------------------

In [4]:
df=pd.read_csv(r"C:\Users\Pratik\Downloads\Superstore.csv",encoding='latin1')

In [5]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Discount Status,Profit Status,Is Profitable,Sales Per Unit
0,1,CA-2013-152156,09/11/13,12/11/13,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,No Discount,Profit,True,130.9800
1,2,CA-2013-152156,09/11/13,12/11/13,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,No Discount,Profit,True,243.9800
2,3,CA-2013-138688,13/06/13,17/06/13,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,No Discount,Profit,True,7.3100
3,4,US-2012-108966,11/10/12,18/10/12,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,Discounted,Loss,False,191.5155
4,5,US-2012-108966,11/10/12,18/10/12,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,Discounted,Profit,True,11.1840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2011-110422,22/01/11,24/01/11,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,Discounted,Profit,True,8.4160
9990,9991,CA-2014-121258,27/02/14,04/03/14,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,No Discount,Profit,True,45.9800
9991,9992,CA-2014-121258,27/02/14,04/03/14,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,Discounted,Profit,True,129.2880
9992,9993,CA-2014-121258,27/02/14,04/03/14,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,No Discount,Profit,True,7.4000
9993,9994,CA-2014-119914,05/05/14,10/05/14,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,No Discount,Profit,True,121.5800

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Discount Status,Profit Status,Is Profitable,Sales Per Unit
0,1,CA-2013-152156,09/11/13,12/11/13,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,No Discount,Profit,True,130.9800
1,2,CA-2013-152156,09/11/13,12/11/13,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,No Discount,Profit,True,243.9800
2,3,CA-2013-138688,13/06/13,17/06/13,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,No Discount,Profit,True,7.3100
3,4,US-2012-108966,11/10/12,18/10/12,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,Discounted,Loss,False,191.5155
4,5,US-2012-108966,11/10/12,18/10/12,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,Discounted,Profit,True,11.1840

In [7]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Discount Status', 'Profit Status', 'Is Profitable', 'Sales Per Unit'],
      dtype='object')

In [8]:
df.shape

(9994, 25)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Row ID           9994 non-null   int64
 1   Order ID         9994 non-null   object
 2   Order Date       9994 non-null   object
 3   Ship Date        9994 non-null   object
 4   Ship Mode        9994 non-null   object
 5   Customer ID      9994 non-null   object
 6   Customer Name    9994 non-null   object
 7   Segment          9994 non-null   object
 8   Country          9994 non-null   object
 9   City             9994 non-null   object
 10  State            9994 non-null   object
 11  Postal Code      9994 non-null   int64
 12  Region           9994 non-null   object
 13  Product ID       9994 non-null   object
 14  Category         9994 non-null   object
 15  Sub-Category     9994 non-null   object
 16  Product Name     9994 non-null   object
 17  Sales            9994 non-null   float64
 18  Quantity         9994 non-null   int64
 19  Discount         9994 non-null   float64
 20  Profit           9994 non-null   float64
 21  Discount Status  9994 non-null   object
 22  Profit Status    9994 non-null   object
 23  Is Profitable    9994 non-null   bool
 24  Sales Per Unit   9994 non-null   float64
dtypes: bool(1), float64(4), int64(3), object(17)
memory usage: 1.8+ MB

In [10]:
df.isna().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country            0
City               0
State              0
Postal Code        0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
Discount Status    0
Profit Status      0
Is Profitable      0
Sales Per Unit     0
dtype: int64

In [11]:
df[df.duplicated()]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Discount Status, Profit Status, Is Profitable, Sales Per Unit]
Index: []

[0 rows x 25 columns]

In [12]:
df.dtypes

Row ID               int64
Order ID            object
Order Date          object
Ship Date           object
Ship Mode           object
Customer ID         object
Customer Name       object
Segment             object
Country             object
City                object
State               object
Postal Code          int64
Region              object
Product ID          object
Category            object
Sub-Category        object
Product Name        object
Sales              float64
Quantity             int64
Discount           float64
Profit             float64
Discount Status     object
Profit Status       object
Is Profitable         bool
Sales Per Unit     float64
dtype: object

In [13]:
Total_sales=df['Sales'].sum()

In [14]:
Total_sales

np.float64(2297200.8603000003)

In [15]:
Total_profit=df['Profit'].sum()

In [16]:
Total_profit

np.float64(286397.0217)

In [17]:
Total_quantity_sold=df['Quantity'].sum()
Total_quantity_sold

np.int64(37873)

In [18]:
Avg_sales=df['Sales'].mean()
Avg_sales

np.float64(229.85800083049833)

In [19]:
Avg_profit=df['Profit'].mean()
Avg_profit

np.float64(28.65689630778467)

In [20]:
df2=df[['Customer Name','Segment',
'City',
'State',
'Category',
'Sales',
'Profit']]

In [21]:
df2.head()

,Customer Name,Segment,City,State,Category,Sales,Profit
0,Claire Gute,Consumer,Henderson,Kentucky,Furniture,261.9600,41.9136
1,Claire Gute,Consumer,Henderson,Kentucky,Furniture,731.9400,219.5820
2,Darrin Van Huff,Corporate,Los Angeles,California,Office Supplies,14.6200,6.8714
3,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,Furniture,957.5775,-383.0310
4,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,Office Supplies,22.3680,2.5164

In [22]:
df2[df2['Sales']>500]

,Customer Name,Segment,City,State,Category,Sales,Profit
1,Claire Gute,Consumer,Henderson,Kentucky,Furniture,731.9400,219.5820
3,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,Furniture,957.5775,-383.0310
7,Brosina Hoffman,Consumer,Los Angeles,California,Technology,907.1520,90.7152
10,Brosina Hoffman,Consumer,Los Angeles,California,Furniture,1706.1840,85.3092
11,Brosina Hoffman,Consumer,Los Angeles,California,Technology,911.4240,68.3568
...,...,...,...,...,...,...,...
9931,Keith Herrera,Consumer,San Bernardino,California,Furniture,683.3320,-40.1960
9942,Maribeth Dona,Consumer,Anaheim,California,Office Supplies,998.8200,29.9646
9947,Helen Wasserman,Corporate,Indianapolis,Indiana,Furniture,1925.8800,539.2464
9948,Helen Wasserman,Corporate,Indianapolis,Indiana,Office Supplies,2405.2000,793.7160
9968,Richard Bierner,Consumer,Plainfield,New Jersey,Office Supplies,735.9800,331.1910

In [23]:
df2[df2['Profit']>100]

,Customer Name,Segment,City,State,Category,Sales,Profit
1,Claire Gute,Consumer,Henderson,Kentucky,Furniture,731.940,219.5820
13,Irene Maddox,Consumer,Seattle,Washington,Office Supplies,407.976,132.5922
24,Emily Burns,Consumer,Orem,Utah,Furniture,1044.630,240.2649
35,Gene Hale,Corporate,Richardson,Texas,Technology,1097.544,123.4737
54,Janet Molinari,Corporate,New York City,New York,Technology,1029.950,298.6855
...,...,...,...,...,...,...,...
9947,Helen Wasserman,Corporate,Indianapolis,Indiana,Furniture,1925.880,539.2464
9948,Helen Wasserman,Corporate,Indianapolis,Indiana,Office Supplies,2405.200,793.7160
9957,Kristina Nunn,Home Office,New Rochelle,New York,Office Supplies,223.920,109.7208
9968,Richard Bierner,Consumer,Plainfield,New Jersey,Office Supplies,735.980,331.1910
9979,Anne Pryor,Home Office,Los Angeles,California,Office Supplies,437.472,153.1152

In [24]:
df[df['Discount']>0]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Discount Status,Profit Status,Is Profitable,Sales Per Unit
3,4,US-2012-108966,11/10/12,18/10/12,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,Discounted,Loss,False,191.5155
4,5,US-2012-108966,11/10/12,18/10/12,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,Discounted,Profit,True,11.1840
7,8,CA-2011-115812,09/06/11,14/06/11,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152,Discounted,Profit,True,151.1920
8,9,CA-2011-115812,09/06/11,14/06/11,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825,Discounted,Profit,True,6.1680
10,11,CA-2011-115812,09/06/11,14/06/11,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092,Discounted,Profit,True,189.5760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9978,9979,US-2013-103674,07/12/13,11/12/13,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,Binders,Avery Durable Slant Ring Binders With Label Ho...,13.3760,4,0.20,4.6816,Discounted,Profit,True,3.3440
9979,9980,US-2013-103674,07/12/13,11/12/13,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,Binders,Ibico Recycled Linen-Style Covers,437.4720,14,0.20,153.1152,Discounted,Profit,True,31.2480
9981,9982,CA-2014-163566,04/08/14,07/08/14,First Class,TB-21055,Ted Butterfield,Consumer,United States,Fairfield,...,Labels,Avery 476,16.5200,5,0.20,5.3690,Discounted,Profit,True,3.3040
9989,9990,CA-2011-110422,22/01/11,24/01/11,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,Discounted,Profit,True,8.4160
9991,9992,CA-2014-121258,27/02/14,04/03/14,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,Discounted,Profit,True,129.2880

In [25]:
df[(df['Sales']>500) &(df['Profit']<0)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Discount Status,Profit Status,Is Profitable,Sales Per Unit
3,4,US-2012-108966,11/10/12,18/10/12,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,Discounted,Loss,False,191.5155
27,28,US-2012-150630,17/09/12,21/09/12,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522,Discounted,Loss,False,440.4900
38,39,CA-2012-117415,27/12/12,31/12/12,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,Bookcases,"Atlantic Metals Mobile 3-Shelf Bookcases, Cust...",532.3992,3,0.32,-46.9764,Discounted,Loss,False,177.4664
72,73,US-2012-134026,26/04/12,02/05/12,Standard Class,JE-15745,Joel Eaton,Consumer,United States,Memphis,...,Chairs,High-Back Leather Manager's Chair,831.9360,8,0.20,-114.3912,Discounted,Loss,False,103.9920
124,125,US-2011-152030,26/12/11,28/12/11,Second Class,AD-10180,Alan Dominguez,Home Office,United States,Houston,...,Chairs,Global Deluxe High-Back Manager's Chair,600.5580,3,0.30,-8.5794,Discounted,Loss,False,200.1860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9788,9789,CA-2014-144491,28/03/14,02/04/14,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,...,Chairs,Global Deluxe High-Back Manager's Chair,600.5580,3,0.30,-8.5794,Discounted,Loss,False,200.1860
9816,9817,CA-2012-162201,08/06/12,12/06/12,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Saint Petersburg,...,Storage,Fellowes Super Stor/Drawer Files,516.9600,4,0.20,-6.4620,Discounted,Loss,False,129.2400
9876,9877,US-2014-166324,21/04/14,22/04/14,First Class,BE-11455,Brad Eason,Home Office,United States,Cleveland,...,Storage,Tennsco 6- and 18-Compartment Lockers,848.5440,4,0.20,-21.2136,Discounted,Loss,False,212.1360
9919,9920,CA-2013-149272,16/03/13,20/03/13,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,...,Chairs,Novimex Swivel Fabric Task Chair,528.4300,5,0.30,-143.4310,Discounted,Loss,False,105.6860
9931,9932,CA-2012-104948,13/11/12,17/11/12,Standard Class,KH-16510,Keith Herrera,Consumer,United States,San Bernardino,...,Bookcases,O'Sullivan Living Dimensions 3-Shelf Bookcases,683.3320,4,0.15,-40.1960,Discounted,Loss,False,170.8330

In [26]:
df.sort_values(by='Sales',ascending=False)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Discount Status,Profit Status,Is Profitable,Sales Per Unit
2697,2698,CA-2011-145317,18/03/11,23/03/11,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784,Discounted,Loss,False,3773.080
6826,6827,CA-2013-118689,03/10/13,10/10/13,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,No Discount,Profit,True,3499.990
8153,8154,CA-2014-140151,24/03/14,26/03/14,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808,No Discount,Profit,True,3499.990
2623,2624,CA-2014-127180,23/10/14,25/10/14,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888,Discounted,Profit,True,2799.992
4190,4191,CA-2014-166709,18/11/14,23/11/14,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856,No Discount,Profit,True,3499.990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,2107,US-2011-152723,26/09/11,26/09/11,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,...,Binders,Acco 3-Hole Punch,0.876,1,0.8,-1.4016,Discounted,Loss,False,0.876
4711,4712,CA-2011-112403,31/03/11,31/03/11,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,...,Binders,Avery Round Ring Poly Binders,0.852,1,0.7,-0.5964,Discounted,Loss,False,0.852
8658,8659,CA-2013-168361,22/06/13,26/06/13,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,...,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836,1,0.8,-1.3376,Discounted,Loss,False,0.836
9292,9293,CA-2014-124114,03/03/14,03/03/14,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,...,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556,1,0.8,-0.9452,Discounted,Loss,False,0.556
4101,4102,US-2014-102288,20/06/14,24/06/14,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,...,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,Discounted,Loss,False,0.444

In [27]:
df.sort_values(by='Sales',ascending=True)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Discount Status,Profit Status,Is Profitable,Sales Per Unit
4101,4102,US-2014-102288,20/06/14,24/06/14,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,...,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,Discounted,Loss,False,0.444
9292,9293,CA-2014-124114,03/03/14,03/03/14,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,...,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556,1,0.8,-0.9452,Discounted,Loss,False,0.556
8658,8659,CA-2013-168361,22/06/13,26/06/13,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,...,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836,1,0.8,-1.3376,Discounted,Loss,False,0.836
4711,4712,CA-2011-112403,31/03/11,31/03/11,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,...,Binders,Avery Round Ring Poly Binders,0.852,1,0.7,-0.5964,Discounted,Loss,False,0.852
2106,2107,US-2011-152723,26/09/11,26/09/11,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,...,Binders,Acco 3-Hole Punch,0.876,1,0.8,-1.4016,Discounted,Loss,False,0.876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4190,4191,CA-2014-166709,18/11/14,23/11/14,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856,No Discount,Profit,True,3499.990
2623,2624,CA-2014-127180,23/10/14,25/10/14,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888,Discounted,Profit,True,2799.992
8153,8154,CA-2014-140151,24/03/14,26/03/14,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808,No Discount,Profit,True,3499.990
6826,6827,CA-2013-118689,03/10/13,10/10/13,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,No Discount,Profit,True,3499.990
2697,2698,CA-2011-145317,18/03/11,23/03/11,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784,Discounted,Loss,False,3773.080

In [28]:
df.sort_values(by=['Category','Sales'],ascending=[True,False])

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Discount Status,Profit Status,Is Profitable,Sales Per Unit
7243,7244,CA-2014-118892,18/08/14,23/08/14,Second Class,TP-21415,Tom Prescott,Consumer,United States,Philadelphia,...,Chairs,HON 5400 Series Task Chairs for Big and Tall,4416.174,9,0.3,-630.8820,Discounted,Loss,False,490.686
9741,9742,CA-2012-117086,08/11/12,12/11/12,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,...,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.900,5,0.0,1013.1270,No Discount,Profit,True,880.980
9639,9640,CA-2012-116638,28/01/12,31/01/12,Second Class,JH-15985,Joseph Holt,Consumer,United States,Concord,...,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,Discounted,Loss,False,330.588
5917,5918,US-2012-126977,17/09/12,23/09/12,Standard Class,PF-19120,Peter Fuller,Consumer,United States,New York City,...,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4228.704,6,0.2,158.5764,Discounted,Profit,True,704.784
6535,6536,CA-2011-128209,17/11/11,22/11/11,Standard Class,GT-14710,Greg Tran,Consumer,United States,Buffalo,...,Bookcases,DMI Eclipse Executive Suite Bookcases,4007.840,10,0.2,-50.0980,Discounted,Loss,False,400.784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9163,9164,CA-2012-164007,08/06/12,12/06/12,Standard Class,MG-17695,Maureen Gnade,Consumer,United States,Chicago,...,Accessories,Maxell 4.7GB DVD+R 5/Pack,2.376,3,0.2,0.7425,Discounted,Profit,True,0.792
7990,7991,US-2013-117793,24/08/13,30/08/13,Standard Class,MA-17560,Matt Abelman,Home Office,United States,Sheboygan,...,Accessories,Maxell 4.7GB DVD+R 5/Pack,1.980,2,0.0,0.8910,No Discount,Profit,True,0.990
9545,9546,CA-2011-166590,29/10/11,02/11/11,Standard Class,NC-18625,Noah Childs,Corporate,United States,Columbus,...,Accessories,Maxell 4.7GB DVD+R 5/Pack,1.980,2,0.0,0.8910,No Discount,Profit,True,0.990
7900,7901,CA-2014-128363,14/08/14,19/08/14,Standard Class,DC-12850,Dan Campbell,Consumer,United States,Memphis,...,Accessories,Maxell 4.7GB DVD-R 5/Pack,1.584,2,0.2,0.4752,Discounted,Profit,True,0.792
2761,2762,CA-2014-126536,13/10/14,15/10/14,First Class,NK-18490,Neil Knudson,Home Office,United States,San Francisco,...,Accessories,Maxell 4.7GB DVD-R 5/Pack,0.990,1,0.0,0.4356,No Discount,Profit,True,0.990

In [29]:
df.isnull().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country            0
City               0
State              0
Postal Code        0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
Discount Status    0
Profit Status      0
Is Profitable      0
Sales Per Unit     0
dtype: int64

In [30]:
df.isna().sum().sum()

np.int64(0)

In [31]:
df.columns[df.isnull().any()]

Index([], dtype='object')

In [32]:
df['Customer ID'].nunique()

793

In [33]:
df['Product ID'].nunique()

1862

In [34]:
df['City'].nunique()

531

In [35]:
df['Sub-Category'].unique()

array(['Bookcases', 'Chairs', 'Labels', 'Tables', 'Storage',
       'Furnishings', 'Art', 'Phones', 'Binders', 'Appliances', 'Paper',
       'Accessories', 'Envelopes', 'Fasteners', 'Supplies', 'Machines',
       'Copiers'], dtype=object)

In [36]:
df['Region'].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

In [37]:
#value_counts

In [38]:
df['Category'].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [39]:
df['Sub-Category'].value_counts()

Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [40]:
df['Segment'].value_counts()

Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

In [41]:
df['Region'].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [42]:
df['Ship Mode'].value_counts()

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

In [43]:
df['Profit Status'].value_counts()

Profit Status
Profit    8058
Loss      1936
Name: count, dtype: int64

In [44]:
df['Discount Status'].value_counts()

Discount Status
Discounted     5196
No Discount    4798
Name: count, dtype: int64

In [45]:
df['Profit_Margin']=(df['Profit']/df['Sales'])*100

In [46]:
df[['Product Name','Sales','Profit','Profit_Margin']]

,Product Name,Sales,Profit,Profit_Margin
0,Bush Somerset Collection Bookcase,261.9600,41.9136,16.00
1,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,219.5820,30.00
2,Self-Adhesive Address Labels for Typewriters b...,14.6200,6.8714,47.00
3,Bretford CR4500 Series Slim Rectangular Table,957.5775,-383.0310,-40.00
4,Eldon Fold 'N Roll Cart System,22.3680,2.5164,11.25
...,...,...,...,...
9989,Ultra Door Pull Handle,25.2480,4.1028,16.25
9990,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,15.6332,17.00
9991,Aastra 57i VoIP phone,258.5760,19.3932,7.50
9992,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,13.3200,45.00
9993,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,72.9480,30.00

In [47]:
def seles_level(sales):
    if sales<100:
        return "Low"

    elif sales>=100 and sales<=500:
        return "Medium"

    else:
        return "High"

In [48]:
df['Sales Level']=df['Sales'].apply(seles_level)

In [49]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Discount Status,Profit Status,Is Profitable,Sales Per Unit,Profit_Margin,Sales Level
0,1,CA-2013-152156,09/11/13,12/11/13,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,No Discount,Profit,True,130.9800,16.00,Medium
1,2,CA-2013-152156,09/11/13,12/11/13,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,No Discount,Profit,True,243.9800,30.00,High
2,3,CA-2013-138688,13/06/13,17/06/13,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,No Discount,Profit,True,7.3100,47.00,Low
3,4,US-2012-108966,11/10/12,18/10/12,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,Discounted,Loss,False,191.5155,-40.00,High
4,5,US-2012-108966,11/10/12,18/10/12,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,Discounted,Profit,True,11.1840,11.25,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2011-110422,22/01/11,24/01/11,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,25.2480,3,0.20,4.1028,Discounted,Profit,True,8.4160,16.25,Low
9990,9991,CA-2014-121258,27/02/14,04/03/14,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,91.9600,2,0.00,15.6332,No Discount,Profit,True,45.9800,17.00,Low
9991,9992,CA-2014-121258,27/02/14,04/03/14,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,258.5760,2,0.20,19.3932,Discounted,Profit,True,129.2880,7.50,Medium
9992,9993,CA-2014-121258,27/02/14,04/03/14,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,29.6000,4,0.00,13.3200,No Discount,Profit,True,7.4000,45.00,Low
9993,9994,CA-2014-119914,05/05/14,10/05/14,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,243.1600,2,0.00,72.9480,No Discount,Profit,True,121.5800,30.00,Medium

## Groupby

In [50]:
df.groupby('Region')[['Sales','Profit']].sum().sort_values('Profit',ascending=False)

               Sales       Profit
Region
West     725457.8245  108418.4489
East     678781.2400   91522.7800
South    391721.9050   46749.4303
Central  501239.8908   39706.3625

In [51]:
avg_sub_sales=df.groupby('Sub-Category')['Sales'].mean()
avg_sub_sales

Sub-Category
Accessories     215.974604
Appliances      230.755710
Art              34.068834
Binders         133.560560
Bookcases       503.859633
Chairs          532.332420
Copiers        2198.941618
Envelopes        64.867724
Fasteners        13.936774
Furnishings      95.825668
Labels           34.303055
Machines       1645.553313
Paper            57.284092
Phones          371.211534
Storage         264.590553
Supplies        245.650200
Tables          648.794771
Name: Sales, dtype: float64

In [52]:
avg_sub_sales[avg_sub_sales>200]

Sub-Category
Accessories     215.974604
Appliances      230.755710
Bookcases       503.859633
Chairs          532.332420
Copiers        2198.941618
Machines       1645.553313
Phones          371.211534
Storage         264.590553
Supplies        245.650200
Tables          648.794771
Name: Sales, dtype: float64

In [53]:
top10=df.groupby(['Customer ID','Customer Name'])['Sales'].sum()

In [54]:
top10.nlargest(10)

Customer ID  Customer Name
SM-20320     Sean Miller           25043.050
TC-20980     Tamara Chand          19052.218
RB-19360     Raymond Buch          15117.339
TA-21385     Tom Ashbrook          14595.620
AB-10105     Adrian Barton         14473.571
KL-16645     Ken Lonsdale          14175.229
SC-20095     Sanjit Chand          14142.334
HL-15040     Hunter Lopez          12873.298
SE-20110     Sanjit Engle          12209.438
CC-12370     Christopher Conant    12129.072
Name: Sales, dtype: float64

In [55]:
top10=df.groupby(['Customer ID','Customer Name'])['Profit'].sum()

In [56]:
top10.nlargest(10)

Customer ID  Customer Name
TC-20980     Tamara Chand            8981.3239
RB-19360     Raymond Buch            6976.0959
SC-20095     Sanjit Chand            5757.4119
HL-15040     Hunter Lopez            5622.4292
AB-10105     Adrian Barton           5444.8055
TA-21385     Tom Ashbrook            4703.7883
CM-12385     Christopher Martinez    3899.8904
KD-16495     Keith Dawkins           3038.6254
AR-10540     Andy Reiter             2884.6208
DR-12940     Daniel Raglin           2869.0760
Name: Profit, dtype: float64

In [57]:
top10.nsmallest(10)

Customer ID  Customer Name
CS-12505     Cindy Stewart      -6626.3895
GT-14635     Grant Thornton     -4108.6589
LF-17185     Luke Foster        -3583.9770
SR-20425     Sharelle Roach     -3333.9144
HG-14965     Henry Goldwyn      -2797.9635
NC-18415     Nathan Cano        -2204.8072
SB-20290     Sean Braxton       -2082.7451
SM-20320     Sean Miller        -1980.7393
CP-12340     Christine Phan     -1850.3029
NF-18385     Natalie Fritzler   -1695.9714
Name: Profit, dtype: float64

In [58]:
result=df.groupby('Category').agg({
    'Sales':['sum','mean'],
    'Profit':['sum','mean'],
    'Quantity':'sum'
})

In [59]:
print(result)

                       Sales                   Profit            Quantity
                         sum        mean          sum       mean      sum
Category
Furniture        741999.7953  349.834887   18451.2728   8.699327     8028
Office Supplies  719047.0320  119.324101  122490.8008  20.327050    22906
Technology       836154.0330  452.709276  145454.9481  78.752002     6939

In [60]:
df.dtypes

Row ID               int64
Order ID            object
Order Date          object
Ship Date           object
Ship Mode           object
Customer ID         object
Customer Name       object
Segment             object
Country             object
City                object
State               object
Postal Code          int64
Region              object
Product ID          object
Category            object
Sub-Category        object
Product Name        object
Sales              float64
Quantity             int64
Discount           float64
Profit             float64
Discount Status     object
Profit Status       object
Is Profitable         bool
Sales Per Unit     float64
Profit_Margin      float64
Sales Level         object
dtype: object

In [61]:
df['Order Date']=pd.to_datetime(df['Order Date'])

In [62]:
df['Order Date'].dt.year

0       2013
1       2013
2       2013
3       2012
4       2012
        ...
9989    2011
9990    2014
9991    2014
9992    2014
9993    2014
Name: Order Date, Length: 9994, dtype: int32

In [63]:
df['Order Date'].dt.month

0        9
1        9
2        6
3       11
4       11
        ..
9989     1
9990     2
9991     2
9992     2
9993     5
Name: Order Date, Length: 9994, dtype: int32

In [64]:
df['Order Date'].dt.month_name()

0       September
1       September
2            June
3        November
4        November
          ...
9989      January
9990     February
9991     February
9992     February
9993          May
Name: Order Date, Length: 9994, dtype: object

In [65]:
df['Order Date'].dt.day

0       11
1       11
2       13
3       10
4       10
        ..
9989    22
9990    27
9991    27
9992    27
9993     5
Name: Order Date, Length: 9994, dtype: int32

In [66]:
df['Order Date'].dt.dayofweek

0       2
1       2
2       3
3       5
4       5
       ..
9989    5
9990    3
9991    3
9992    3
9993    0
Name: Order Date, Length: 9994, dtype: int32

In [67]:
df['Order Date'].dt.day_name()

0       Wednesday
1       Wednesday
2        Thursday
3        Saturday
4        Saturday
          ...
9989     Saturday
9990     Thursday
9991     Thursday
9992     Thursday
9993       Monday
Name: Order Date, Length: 9994, dtype: object

In [68]:
df['Order Date'].dt.quarter

0       3
1       3
2       2
3       4
4       4
       ..
9989    1
9990    1
9991    1
9992    1
9993    2
Name: Order Date, Length: 9994, dtype: int32

In [69]:
df['Order Date'].dt.quarter

0       3
1       3
2       2
3       4
4       4
       ..
9989    1
9990    1
9991    1
9992    1
9993    2
Name: Order Date, Length: 9994, dtype: int32

In [70]:
df['Order Date'].dt.quarter

0       3
1       3
2       2
3       4
4       4
       ..
9989    1
9990    1
9991    1
9992    1
9993    2
Name: Order Date, Length: 9994, dtype: int32

In [71]:
df['Order Date'].dt.quarter

0       3
1       3
2       2
3       4
4       4
       ..
9989    1
9990    1
9991    1
9992    1
9993    2
Name: Order Date, Length: 9994, dtype: int32

In [72]:
df['Order Date'].dt.quarter

0       3
1       3
2       2
3       4
4       4
       ..
9989    1
9990    1
9991    1
9992    1
9993    2
Name: Order Date, Length: 9994, dtype: int32

In [73]:
df.dtypes

Row ID                      int64
Order ID                   object
Order Date         datetime64[ns]
Ship Date                  object
Ship Mode                  object
Customer ID                object
Customer Name              object
Segment                    object
Country                    object
City                       object
State                      object
Postal Code                 int64
Region                     object
Product ID                 object
Category                   object
Sub-Category               object
Product Name               object
Sales                     float64
Quantity                    int64
Discount                  float64
Profit                    float64
Discount Status            object
Profit Status              object
Is Profitable                bool
Sales Per Unit            float64
Profit_Margin             float64
Sales Level                object
dtype: object

In [74]:
df['Ship Date']=pd.to_datetime(df['Ship Date'])

In [75]:
df['Order Year']=df['Order Date'].dt.year
df['Order Month']=df['Order Date'].dt.month
    
df['Order Day']=df['Order Date'].dt.day

In [76]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Profit,Discount Status,Profit Status,Is Profitable,Sales Per Unit,Profit_Margin,Sales Level,Order Year,Order Month,Order Day
0,1,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,41.9136,No Discount,Profit,True,130.9800,16.00,Medium,2013,9,11
1,2,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,219.5820,No Discount,Profit,True,243.9800,30.00,High,2013,9,11
2,3,CA-2013-138688,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,6.8714,No Discount,Profit,True,7.3100,47.00,Low,2013,6,13
3,4,US-2012-108966,2012-11-10,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,-383.0310,Discounted,Loss,False,191.5155,-40.00,High,2012,11,10
4,5,US-2012-108966,2012-11-10,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,2.5164,Discounted,Profit,True,11.1840,11.25,Low,2012,11,10

In [77]:
df['Order Month Name']=df['Order Date'].dt.month_name()

In [78]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Discount Status,Profit Status,Is Profitable,Sales Per Unit,Profit_Margin,Sales Level,Order Year,Order Month,Order Day,Order Month Name
0,1,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,No Discount,Profit,True,130.9800,16.00,Medium,2013,9,11,September
1,2,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,No Discount,Profit,True,243.9800,30.00,High,2013,9,11,September
2,3,CA-2013-138688,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,No Discount,Profit,True,7.3100,47.00,Low,2013,6,13,June
3,4,US-2012-108966,2012-11-10,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Discounted,Loss,False,191.5155,-40.00,High,2012,11,10,November
4,5,US-2012-108966,2012-11-10,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Discounted,Profit,True,11.1840,11.25,Low,2012,11,10,November

In [79]:
var=df.groupby('Order Month Name')['Sales'].sum()
var

Order Month Name
April        154316.7811
August       207760.1943
December     253639.8997
February     120374.9094
January      137587.1322
July         149362.7248
June         146105.1243
March        237482.7502
May          175243.4649
November     271461.7345
October      177756.4052
September    266109.7397
Name: Sales, dtype: float64

In [80]:
var=df.groupby('Order Month Name')['Sales'].sum().idxmax()
var

'November'

In [81]:
df['Shipping Days']=df['Ship Date']-df['Order Date']

In [82]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Profit Status,Is Profitable,Sales Per Unit,Profit_Margin,Sales Level,Order Year,Order Month,Order Day,Order Month Name,Shipping Days
0,1,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Profit,True,130.9800,16.00,Medium,2013,9,11,September,91 days
1,2,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Profit,True,243.9800,30.00,High,2013,9,11,September,91 days
2,3,CA-2013-138688,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Profit,True,7.3100,47.00,Low,2013,6,13,June,4 days
3,4,US-2012-108966,2012-11-10,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Loss,False,191.5155,-40.00,High,2012,11,10,November,-23 days
4,5,US-2012-108966,2012-11-10,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Profit,True,11.1840,11.25,Low,2012,11,10,November,-23 days

In [83]:
df['Shipping Days'].min()

Timedelta('-320 days +00:00:00')

In [84]:
table=df.groupby(['Category','Region'])['Profit'].sum()

In [85]:
table

Category         Region
Furniture        Central    -2871.0494
                 East        3046.1658
                 South       6771.2061
                 West       11504.9503
Office Supplies  Central     8879.9799
                 East       41014.5791
                 South      19986.3928
                 West       52609.8490
Technology       Central    33697.4320
                 East       47462.0351
                 South      19991.8314
                 West       44303.6496
Name: Profit, dtype: float64

In [86]:
df.groupby(['Category', 'Region'])['Profit'].sum().reset_index()

           Category   Region      Profit
0         Furniture  Central  -2871.0494
1         Furniture     East   3046.1658
2         Furniture    South   6771.2061
3         Furniture     West  11504.9503
4   Office Supplies  Central   8879.9799
5   Office Supplies     East  41014.5791
6   Office Supplies    South  19986.3928
7   Office Supplies     West  52609.8490
8        Technology  Central  33697.4320
9        Technology     East  47462.0351
10       Technology    South  19991.8314
11       Technology     West  44303.6496

In [87]:
df.pivot_table(
    index='Category',
    columns='Region',
    values='Profit',
    aggfunc='sum'
)

Region              Central        East       South        West
Category
Furniture        -2871.0494   3046.1658   6771.2061  11504.9503
Office Supplies   8879.9799  41014.5791  19986.3928  52609.8490
Technology       33697.4320  47462.0351  19991.8314  44303.6496

In [88]:
df.pivot_table(
    index='Region',
    columns='Category',
    values='Sales',
    aggfunc='sum'
)

Category    Furniture  Office Supplies  Technology
Region
Central   163797.1638       167026.415  170416.312
East      208291.2040       205516.055  264973.981
South     117298.6840       125651.313  148771.908
West      252612.7435       220853.249  251991.832

In [89]:
# most profitable product

In [90]:
df.groupby('Product Name')['Profit'].sum().nlargest(10)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          25199.9280
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.0390
Hewlett Packard LaserJet 3310 Copier                                            6983.8836
Canon PC1060 Personal Laser Copier                                              4570.9347
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.9766
Ativa V4110MDD Micro-Cut Shredder                                               3772.9461
3D Systems Cube Printer, 2nd Generation, Magenta                                3717.9714
Plantronics Savi W720 Multi-Device Wireless Headset System                      3696.2820
Ibico EPK-21 Electric Binding System                                            3345.2823
Zebra ZM400 Thermal Label Printer                                               3343.5360
Name: Profit, dtype: float64

In [91]:
result=df.groupby('Product Name').agg(
    total_Sales=('Sales','sum'),
    total_profit=('Profit','sum')
)

In [92]:
result[(result['total_Sales']>1000)&(result['total_profit']<0)]

                                                    total_Sales  total_profit
Product Name
3.6 Cubic Foot Counter Height Office Refrigerator     2946.2000     -872.0752
3D Systems Cube Printer, 2nd Generation, White        2339.9820     -467.9964
Atlantic Metals Mobile 4-Shelf Bookcases, Custo...    5184.0810     -126.4410
BPI Conference Tables                                 2241.8675     -795.9725
Balt Solid Wood Round Tables                          6518.7540    -1201.0581
...                                                         ...           ...
Tennsco Industrial Shelving                           1281.4420     -108.5802
Tennsco Regal Shelving Units                          1764.5340       -6.0846
Tennsco Single-Tier Lockers                           9158.2960     -825.7480
Tennsco Stur-D-Stor Boltless Shelving, 5 Shelve...    4384.0440      -36.5337
Xerox WorkCentre 6505DN Laser Multifunction Pri...    2519.9580     -251.9958

[139 rows x 2 columns]

In [93]:
#Q25. Average Profit by Discount Level

In [94]:
result=df.groupby('Discount').agg(
    Avg_profit=('Profit','mean'),
    record_count=('Profit','count')
)
result

          Avg_profit  record_count
Discount
0.00       66.900292          4798
0.10       96.055074            94
0.15       27.288298            52
0.20       24.702572          3657
0.30      -45.679636           227
0.32      -88.560656            27
0.40     -111.927429           206
0.45     -226.646464            11
0.50     -310.703456            66
0.60      -43.077212           138
0.70      -95.874060           418
0.80     -101.796797           300

In [95]:
result=df.groupby('Discount').agg(
    Avg_profit=('Profit','mean'),
    record_count=('Profit','count')
)
result

          Avg_profit  record_count
Discount
0.00       66.900292          4798
0.10       96.055074            94
0.15       27.288298            52
0.20       24.702572          3657
0.30      -45.679636           227
0.32      -88.560656            27
0.40     -111.927429           206
0.45     -226.646464            11
0.50     -310.703456            66
0.60      -43.077212           138
0.70      -95.874060           418
0.80     -101.796797           300

In [96]:
profit_margin = df['Profit'].sum()/ df['Sales'].sum() *100

In [97]:
profit_margin

np.float64(12.467217240315604)

In [98]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Profit Status,Is Profitable,Sales Per Unit,Profit_Margin,Sales Level,Order Year,Order Month,Order Day,Order Month Name,Shipping Days
0,1,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Profit,True,130.9800,16.00,Medium,2013,9,11,September,91 days
1,2,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Profit,True,243.9800,30.00,High,2013,9,11,September,91 days
2,3,CA-2013-138688,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Profit,True,7.3100,47.00,Low,2013,6,13,June,4 days
3,4,US-2012-108966,2012-11-10,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Loss,False,191.5155,-40.00,High,2012,11,10,November,-23 days
4,5,US-2012-108966,2012-11-10,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Profit,True,11.1840,11.25,Low,2012,11,10,November,-23 days

In [99]:
res=df.groupby('Customer ID').agg(
    orders=('Order ID','count'),
    total_sales=('Sales','sum'),
    total_profit=('Profit','sum')
    
)

In [100]:
res

             orders  total_sales  total_profit
Customer ID
AA-10315         11     5563.560     -362.8825
AA-10375         15     1056.390      277.3824
AA-10480         12     1790.512      435.8274
AA-10645         18     5086.935      857.8033
AB-10015          6      886.156      129.3465
...             ...          ...           ...
XP-21865         28     2374.658      621.2300
YC-21895          8     5454.350     1305.6290
YS-21880         12     6720.444     1778.2923
ZC-21910         31     8025.707    -1032.1490
ZD-21925          9     1493.944      249.1307

[793 rows x 3 columns]

In [101]:
res=res[
    (res['orders']>=10)&
    (res['total_sales']>5000)&
    (res['total_profit']>0)
]

result

          Avg_profit  record_count
Discount
0.00       66.900292          4798
0.10       96.055074            94
0.15       27.288298            52
0.20       24.702572          3657
0.30      -45.679636           227
0.32      -88.560656            27
0.40     -111.927429           206
0.45     -226.646464            11
0.50     -310.703456            66
0.60      -43.077212           138
0.70      -95.874060           418
0.80     -101.796797           300

In [102]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Profit Status,Is Profitable,Sales Per Unit,Profit_Margin,Sales Level,Order Year,Order Month,Order Day,Order Month Name,Shipping Days
0,1,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Profit,True,130.98,16.0,Medium,2013,9,11,September,91 days
1,2,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Profit,True,243.98,30.0,High,2013,9,11,September,91 days

In [103]:
res=df.groupby('Customer Name').agg(
    Number_of_Years=('Order Year','nunique'),
    total_sales=('Sales','sum')

    
)
res[res['Number_of_Years']>1]

                    Number_of_Years  total_sales
Customer Name
Aaron Bergman                     2      886.156
Aaron Hawkins                     4     1744.700
Aaron Smayling                    3     3050.692
Adam Bellavance                   3     7755.620
Adam Hart                         4     3250.337
...                             ...          ...
Xylona Preis                      4     2374.658
Yana Sorensen                     2     6720.444
Yoseph Carroll                    4     5454.350
Zuschuss Carroll                  4     8025.707
Zuschuss Donatelli                3     1493.944

[772 rows x 2 columns]

In [104]:
rest=df.groupby('Customer Name').agg(
    Number_of_Years=('Order Year','nunique'),
    Total_Sales=('Sales','sum')
)

In [105]:
rest

                    Number_of_Years  Total_Sales
Customer Name
Aaron Bergman                     2      886.156
Aaron Hawkins                     4     1744.700
Aaron Smayling                    3     3050.692
Adam Bellavance                   3     7755.620
Adam Hart                         4     3250.337
...                             ...          ...
Xylona Preis                      4     2374.658
Yana Sorensen                     2     6720.444
Yoseph Carroll                    4     5454.350
Zuschuss Carroll                  4     8025.707
Zuschuss Donatelli                3     1493.944

[793 rows x 2 columns]

In [106]:
rest[rest['Number_of_Years']>1]

                    Number_of_Years  Total_Sales
Customer Name
Aaron Bergman                     2      886.156
Aaron Hawkins                     4     1744.700
Aaron Smayling                    3     3050.692
Adam Bellavance                   3     7755.620
Adam Hart                         4     3250.337
...                             ...          ...
Xylona Preis                      4     2374.658
Yana Sorensen                     2     6720.444
Yoseph Carroll                    4     5454.350
Zuschuss Carroll                  4     8025.707
Zuschuss Donatelli                3     1493.944

[772 rows x 2 columns]

In [107]:
sub=df.groupby('Sub-Category').agg(
    Total_Sales=('Sales','sum'),
Total_Profit=('Profit','mean'),
Average_Discount=('Discount','mean'),
Total_Quantity=('Quantity','sum'),
)
sub['Profit_Margin']=(sub['Total_Profit']/sub['Total_Sales'])*100

In [108]:
sub

,Total_Sales,Total_Profit,Average_Discount,Total_Quantity,Profit_Margin
Sub-Category,,,,,
Accessories,167380.3180,54.111788,0.078452,2976,0.032329
Appliances,107532.1610,38.922758,0.166524,1729,0.036196
Art,27118.7920,8.200737,0.074874,3000,0.030240
Binders,203412.7330,19.843574,0.372292,5974,0.009755
Bookcases,114879.9963,-15.230509,0.211140,868,-0.013258
Chairs,328449.1030,43.095894,0.170178,2356,0.013121
Copiers,149528.0300,817.909190,0.161765,234,0.546994
Envelopes,16476.4020,27.418019,0.080315,906,0.166408
Fasteners,3024.2800,4.375660,0.082028,914,0.144684
Furnishings,91705.1640,13.645918,0.138349,3563,0.014880
Labels,12486.3120,15.236962,0.068681,1400,0.122029
Machines,189238.6310,29.432669,0.306087,440,0.015553
Paper,78479.2060,24.856620,0.074891,5178,0.031673
Phones,330007.0540,50.073938,0.154556,3289,0.015174
Storage,223843.6080,25.152277,0.074704,3158,0.011237
Supplies,46673.5380,-6.258418,0.076842,647,-0.013409
Tables,206965.5320,-55.565771,0.261285,1241,-0.026848

In [109]:
sub[sub['Total_Profit']<0]

,Total_Sales,Total_Profit,Average_Discount,Total_Quantity,Profit_Margin
Sub-Category,,,,,
Bookcases,114879.9963,-15.230509,0.211140,868,-0.013258
Supplies,46673.5380,-6.258418,0.076842,647,-0.013409
Tables,206965.5320,-55.565771,0.261285,1241,-0.026848

In [110]:
states=df.groupby('State').agg(
    Total_Sales=('Sales','sum'),
Total_Profit=('Profit','mean'),
Average_Discount=('Discount','mean'),
Total_Quantity=('Quantity','sum'),
)
sub['Profit_Margin']=(sub['Total_Profit']/sub['Total_Sales'])*100

In [111]:
states

,Total_Sales,Total_Profit,Average_Discount,Total_Quantity
State,,,,
Alabama,19510.6400,94.865989,0.000000,256
Arizona,35282.0010,-15.303235,0.303571,862
Arkansas,11678.1300,66.811452,0.000000,240
California,457687.6315,38.171608,0.072764,7667
Colorado,32108.1180,-35.867351,0.316484,693
Connecticut,13384.3570,42.823071,0.007317,281
Delaware,27451.0690,103.930988,0.006250,367
District of Columbia,2865.0200,105.958930,0.000000,40
Florida,89473.7080,-8.875461,0.299347,1379
Georgia,49095.8400,88.315453,0.000000,705
Idaho,4382.4860,39.367767,0.085714,64
Illinois,80166.1010,-25.625787,0.390041,1845
Indiana,53555.3600,123.375411,0.000000,578
Iowa,4579.7600,39.460397,0.000000,112
Kansas,2914.3100,34.851813,0.000000,74
Kentucky,36591.7500,80.573357,0.000000,523
Louisiana,9217.0300,52.288150,0.000000,156
Maine,1270.5300,56.810775,0.000000,35
Maryland,23705.5230,66.963608,0.005714,420
Massachusetts,28634.4340,50.262975,0.015556,491
Michigan,76269.6140,95.934069,0.007059,946
Minnesota,29863.1500,121.608847,0.000000,331
Mississippi,10771.3400,59.867475,0.000000,221
Missouri,22205.1500,97.518341,0.000000,252
Montana,5589.3520,122.221900,0.066667,56
Nebraska,7464.9300,53.607742,0.000000,136
Nevada,16729.1020,85.045279,0.061538,168
New Hampshire,7292.5240,63.203807,0.011111,127
New Jersey,35764.3120,75.176260,0.004615,454
New Mexico,4783.5220,31.273408,0.059459,151
New York,310876.2710,65.637011,0.055319,4224
North Carolina,55603.1640,-30.083985,0.283534,983
North Dakota,919.9100,32.878529,0.000000,30
Ohio,78258.1360,-36.186304,0.324947,1759
Oklahoma,19683.3900,73.544788,0.000000,247
Oregon,17431.1500,-9.600569,0.288710,499
Pennsylvania,116511.9140,-26.507598,0.328620,2153
Rhode Island,22627.9560,130.100523,0.021429,199
South Carolina,8481.7100,42.120395,0.000000,172
South Dakota,1315.5600,32.902358,0.000000,42
Tennessee,30661.8730,-29.189583,0.291257,681
Texas,170188.0458,-26.121174,0.370193,3724
Utah,11220.0560,48.047802,0.060377,219
Vermont,8929.3700,204.088936,0.000000,50
Virginia,70636.7200,83.026564,0.000000,893
Washington,138641.2700,66.013146,0.064032,1883
West Virginia,1209.8240,46.480400,0.075000,18
Wisconsin,32114.6100,76.380004,0.000000,463
Wyoming,1603.1360,100.196000,0.200000,4

In [112]:
states.sort_values(by='Total_Sales',ascending=False)

,Total_Sales,Total_Profit,Average_Discount,Total_Quantity
State,,,,
California,457687.6315,38.171608,0.072764,7667
New York,310876.2710,65.637011,0.055319,4224
Texas,170188.0458,-26.121174,0.370193,3724
Washington,138641.2700,66.013146,0.064032,1883
Pennsylvania,116511.9140,-26.507598,0.328620,2153
Florida,89473.7080,-8.875461,0.299347,1379
Illinois,80166.1010,-25.625787,0.390041,1845
Ohio,78258.1360,-36.186304,0.324947,1759
Michigan,76269.6140,95.934069,0.007059,946
Virginia,70636.7200,83.026564,0.000000,893
North Carolina,55603.1640,-30.083985,0.283534,983
Indiana,53555.3600,123.375411,0.000000,578
Georgia,49095.8400,88.315453,0.000000,705
Kentucky,36591.7500,80.573357,0.000000,523
New Jersey,35764.3120,75.176260,0.004615,454
Arizona,35282.0010,-15.303235,0.303571,862
Wisconsin,32114.6100,76.380004,0.000000,463
Colorado,32108.1180,-35.867351,0.316484,693
Tennessee,30661.8730,-29.189583,0.291257,681
Minnesota,29863.1500,121.608847,0.000000,331
Massachusetts,28634.4340,50.262975,0.015556,491
Delaware,27451.0690,103.930988,0.006250,367
Maryland,23705.5230,66.963608,0.005714,420
Rhode Island,22627.9560,130.100523,0.021429,199
Missouri,22205.1500,97.518341,0.000000,252
Oklahoma,19683.3900,73.544788,0.000000,247
Alabama,19510.6400,94.865989,0.000000,256
Oregon,17431.1500,-9.600569,0.288710,499
Nevada,16729.1020,85.045279,0.061538,168
Connecticut,13384.3570,42.823071,0.007317,281
Arkansas,11678.1300,66.811452,0.000000,240
Utah,11220.0560,48.047802,0.060377,219
Mississippi,10771.3400,59.867475,0.000000,221
Louisiana,9217.0300,52.288150,0.000000,156
Vermont,8929.3700,204.088936,0.000000,50
South Carolina,8481.7100,42.120395,0.000000,172
Nebraska,7464.9300,53.607742,0.000000,136
New Hampshire,7292.5240,63.203807,0.011111,127
Montana,5589.3520,122.221900,0.066667,56
New Mexico,4783.5220,31.273408,0.059459,151
Iowa,4579.7600,39.460397,0.000000,112
Idaho,4382.4860,39.367767,0.085714,64
Kansas,2914.3100,34.851813,0.000000,74
District of Columbia,2865.0200,105.958930,0.000000,40
Wyoming,1603.1360,100.196000,0.200000,4
South Dakota,1315.5600,32.902358,0.000000,42
Maine,1270.5300,56.810775,0.000000,35
West Virginia,1209.8240,46.480400,0.075000,18
North Dakota,919.9100,32.878529,0.000000,30

In [113]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Discount Status', 'Profit Status', 'Is Profitable', 'Sales Per Unit',
       'Profit_Margin', 'Sales Level', 'Order Year', 'Order Month',
       'Order Day', 'Order Month Name', 'Shipping Days'],
      dtype='object')

In [114]:
sales=df.groupby(['Category','Product Name'])['Sales'].sum().reset_index()

In [115]:
sales

        Category                                       Product Name     Sales
0      Furniture                   12-1/2 Diameter Round Wall Clock   551.448
1      Furniture                           24-Hour Round Wall Clock   487.512
2      Furniture                           36X48 HARDFLOOR CHAIRMAT   369.248
3      Furniture                   3M Hangers With Command Adhesive   108.040
4      Furniture                 3M Polarizing Light Filter Sleeves   216.340
...          ...                                                ...       ...
1837  Technology  iKross Bluetooth Portable Keyboard + Cell Phon...   477.660
1838  Technology                         iOttie HLCRIO102 Car Mount   215.892
1839  Technology                                iOttie XL Car Mount   223.888
1840  Technology  invisibleSHIELD by ZAGG Smudge-Free Screen Pro...   442.554
1841  Technology                 netTALK DUO VoIP Telephone Service  1112.788

[1842 rows x 3 columns]

In [116]:
result=sales.loc[
    sales.groupby('Category')['Sales'].idxmax()
]

In [117]:
result

,Category,Product Name,Sales
206,Furniture,HON 5400 Series Task Chairs for Big and Tall,21870.576
773,Office Supplies,Fellowes PB500 Electric Punch Plastic Comb Bin...,27453.384
1486,Technology,Canon imageCLASS 2200 Advanced Copier,61599.824

In [118]:

ff=df.groupby(['Region','Customer Name'])['Profit'].sum().reset_index()

In [119]:
ff

       Region       Customer Name     Profit
0     Central       Aaron Bergman   114.3432
1     Central      Aaron Smayling  -251.2959
2     Central     Adam Bellavance   115.5072
3     Central           Adam Hart    11.9340
4     Central  Adam Shillingsburg   274.4242
...       ...                 ...        ...
2496     West        Xylona Preis   298.3414
2497     West       Yana Sorensen  1551.5945
2498     West      Yoseph Carroll   382.0575
2499     West    Zuschuss Carroll   346.0942
2500     West  Zuschuss Donatelli    42.4662

[2501 rows x 3 columns]

In [120]:
res=ff.loc[
    ff.groupby('Region')['Profit'].idxmax()
]

In [121]:
res

       Region         Customer Name     Profit
579   Central          Tamara Chand  8745.0635
916      East          Hunter Lopez  5045.8564
1394    South  Christopher Martinez  3197.4580
2354     West          Raymond Buch  6807.0879

In [122]:
loss_percentage=df.groupby('Category')['Profit'].apply(lambda x:(x<0).sum()/len(x)*100)

In [123]:
loss_percentage

Category
Furniture          33.663366
Office Supplies    14.702954
Technology         14.672442
Name: Profit, dtype: float64

In [124]:
loss_per=df.groupby('Category')['Profit'].apply(lambda x:(x<0).sum()/len(x)*100)
loss_per

Category
Furniture          33.663366
Office Supplies    14.702954
Technology         14.672442
Name: Profit, dtype: float64

In [125]:
disc=df.groupby('Discount').agg(
    number_of_orders=('Order ID','nunique'),
    total_Sales=('Sales','sum'),
    total_prof=('Profit','sum'),
    Avg_profit=('Profit','mean')
    
)
disc['loss_making_rec_perc']=(
    df.groupby('Discount')['Profit'].apply(lambda x: (x < 0).mean() * 100)
)
disc

,number_of_orders,total_Sales,total_prof,Avg_profit,loss_making_rec_perc
Discount,,,,,
0.00,2644,1.087908e+06,320987.6032,66.900292,0.000000
0.10,89,5.436935e+04,9029.1770,96.055074,4.255319
0.15,51,2.755852e+04,1418.9915,27.288298,32.692308
0.20,2407,7.645944e+05,90337.3060,24.702572,13.727099
0.30,211,1.032267e+05,-10369.2774,-45.679636,91.629956
0.32,27,1.449346e+04,-2391.1377,-88.560656,100.000000
0.40,185,1.164178e+05,-23057.0504,-111.927429,87.378641
0.45,10,5.484974e+03,-2493.1111,-226.646464,100.000000
0.50,64,5.891854e+04,-20506.4281,-310.703456,100.000000
0.60,127,6.644700e+03,-5944.6552,-43.077212,100.000000
0.70,344,4.062028e+04,-40075.3569,-95.874060,100.000000
0.80,250,1.696376e+04,-30539.0392,-101.796797,100.000000

In [126]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Profit Status,Is Profitable,Sales Per Unit,Profit_Margin,Sales Level,Order Year,Order Month,Order Day,Order Month Name,Shipping Days
0,1,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Profit,True,130.98,16.0,Medium,2013,9,11,September,91 days
1,2,CA-2013-152156,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Profit,True,243.98,30.0,High,2013,9,11,September,91 days

In [127]:
final_summary=df.groupby(['Region','Category']).agg(
    Total_sales=('Sales','sum'),
    Total_profit=('Profit','sum'),
    Total_qnt=('Quantity','sum'),
    Avg_dis=('Discount','mean'),
    number_of_orders=('Order ID','nunique')
)
final_summary

                         Total_sales  Total_profit  Total_qnt   Avg_dis  \
Region  Category
Central Furniture        163797.1638    -2871.0494       1827  0.297380
        Office Supplies  167026.4150     8879.9799       5409  0.252743
        Technology       170416.3120    33697.4320       1544  0.133095
East    Furniture        208291.2040     3046.1658       2214  0.154077
        Office Supplies  205516.0550    41014.5791       6462  0.142932
        Technology       264973.9810    47462.0351       1942  0.143364
South   Furniture        117298.6840     6771.2061       1291  0.121536
        Office Supplies  125651.3130    19986.3928       3800  0.167437
        Technology       148771.9080    19991.8314       1118  0.107850
West    Furniture        252612.7435    11504.9503       2696  0.131400
        Office Supplies  220853.2490    52609.8490       7235  0.093358
        Technology       251991.8320    44303.6496       2335  0.133890

                         number_of_orders
Region  Category
Central Furniture                     403
        Office Supplies               880
        Technology                    356
East    Furniture                     488
        Office Supplies              1074
        Technology                    443
South   Furniture                     278
        Office Supplies               619
        Technology                    255
West    Furniture                     595
        Office Supplies              1169
        Technology                    490

In [128]:
final_summary['Profit Margin %']=final_summary['Total_profit']/final_summary['Total_sales']*100

In [129]:
final_summary

                         Total_sales  Total_profit  Total_qnt   Avg_dis  \
Region  Category
Central Furniture        163797.1638    -2871.0494       1827  0.297380
        Office Supplies  167026.4150     8879.9799       5409  0.252743
        Technology       170416.3120    33697.4320       1544  0.133095
East    Furniture        208291.2040     3046.1658       2214  0.154077
        Office Supplies  205516.0550    41014.5791       6462  0.142932
        Technology       264973.9810    47462.0351       1942  0.143364
South   Furniture        117298.6840     6771.2061       1291  0.121536
        Office Supplies  125651.3130    19986.3928       3800  0.167437
        Technology       148771.9080    19991.8314       1118  0.107850
West    Furniture        252612.7435    11504.9503       2696  0.131400
        Office Supplies  220853.2490    52609.8490       7235  0.093358
        Technology       251991.8320    44303.6496       2335  0.133890

                         number_of_orders  Profit Margin %
Region  Category
Central Furniture                     403        -1.752808
        Office Supplies               880         5.316512
        Technology                    356        19.773595
East    Furniture                     488         1.462455
        Office Supplies              1074        19.956873
        Technology                    443        17.911961
South   Furniture                     278         5.772619
        Office Supplies               619        15.906235
        Technology                    255        13.437908
West    Furniture                     595         4.554382
        Office Supplies              1169        23.821180
        Technology                    490        17.581383

In [130]:
print("The data is analysed with the pandas")

The data is analysed with the pandas